---
# Edit environment variables
- name: Edit the environment
  become: true
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items: "{{ os_environment }}"